---
- hosts: all
  remote_user: k8s
  become: yes
  gather_facts: true

- hosts: haproxy
  remote_user: k8s
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Installation HAProxy
      apt:
        name: haproxy
        state: present
    - name: Copie de la configuration
      template:
        src: templates/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        group: root
        mode: "0644"
    - name: Démarrage HAProxy
      service:
        name: haproxy
        state: restarted
        enabled: yes

- hosts: k8s
  remote_user: k8s
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Installation paquets de base
      apt:
        name:
          - apt-transport-https
          - curl
        state: latest

    - name: Commande modprobe
      shell: |
        cat <<EOF | sudo tee /etc/modules
        overlay
        br_netfilter
        EOF
        modprobe overlay
        modprobe br_netfilter

    - name: Configuration paramètre systemctl
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF

    - name: Ajout des clés GPG des repos
      apt_key:
        url: "{{item}}"
      loop:
        - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{crio.os}}/Release.key"
        - "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{crio.version}}/{{crio.os}}/Release.key"
        - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

    - name: Installation repository
      apt_repository:
        repo: "{{item}}"
        state: present
      loop:
        - "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{crio.os}}/ /"
        - "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{crio.version}}/{{crio.os}}/ /"
        - "deb https://apt.kubernetes.io/ kubernetes-xenial main "

    - name: Installation cri-o et binaires kubernetes
      apt:
        name:
          - cri-o
          - cri-o-runc
          - "kubelet={{kubelet.version}}"
          - "kubeadm={{kubelet.version}}"
          - "kubectl={{kubelet.version}}"
          - open-iscsi
        state: present

    - name: Marquage des paquets pour les binaires kubernetes
      dpkg_selections:
        name: "{{item}}"
        selection: hold
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Start crio
      service:
        name: crio
        state: started
        enabled: yes

    - name: Autoriser le démarrage au boot de kubelet
      service:
        name: kubelet
        enabled: yes

    - name: Start iSCSI
      service:
        name: iscsid
        state: started
        enabled: yes

    - name: modprobe pour iSCSI
      shell: modprobe iscsi_tcp && echo iscsi_tcp >/etc/modules-load.d/iscsi-tcp.conf

    - name: Relancer les règles de sysctl.conf
      command: sysctl --system

- hosts: masters[0]
  remote_user: k8s
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Configuration kubelet
      template:
        src: templates/kubeadm.yaml
        dest: /root/kubeadm.yaml
        group: root
        mode: "0644"

    - name: kubeadm init
      shell: kubeadm init --config /root/kubeadm.yaml --upload-certs
      register: kubeadm_out

    - debug:
        var: kubeadm_out.stdout_lines

    - name: Création du dossier .kube
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: "0700"
    - name: Copie de la config kubectl
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: "0600"

    - name: Installation de Helm
      # FixMe: C'est pas top comme méthode d'installation...
      shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      args:
        warn: no

    - name: Ajout des repos Helm
      shell: helm repo add {{ item }}
      loop:
        - stable https://charts.helm.sh/stable
        - cilium https://helm.cilium.io/
        - openebs https://openebs.github.io/charts
        - falcosecurity https://falcosecurity.github.io/charts
        - loki https://grafana.github.io/loki/charts

    - name: Mise à jour des Charts Helm
      shell: helm repo update

    - name: Récupération de la commande 'kubeadm join' pour les masters
      set_fact:
        kubeadm_masters_join: "{{ kubeadm_out.stdout_lines[-12][:-2]+kubeadm_out.stdout_lines[-11][:-2]+kubeadm_out.stdout_lines[-10] }}"

    - name: Récupération de la commande 'kubeadm join' pour les workers
      set_fact:
        kubeadm_workers_join: "{{ kubeadm_out.stdout_lines[-2][:-2]+kubeadm_out.stdout_lines[-1] }}"

    - name: Petite pause après l'initialisation du cluster...
      pause:
        seconds: "20"

- hosts: masters[1:]
  serial: 1 # Execute le playbook machine par machine
  remote_user: k8s
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: kubeadm join - control plane
      shell: "{{ hostvars[groups['masters'][0]]['kubeadm_masters_join'] }}"

- hosts: workers
  serial: 1 # Execute le playbook machine par machine
  remote_user: k8s
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: kubeadm join - workers
      shell: "{{ hostvars[groups['masters'][0]]['kubeadm_workers_join'] }}"

- hosts: masters[0]
  remote_user: k8s
  become: yes
  vars_files:
    - vars.yml
  tasks:
    # Vérifications
    - name: Vérification des noeuds
      shell: kubectl get nodes
      register: nodes_check
    - debug:
        var: nodes_check.stdout_lines

    # Manifests basiques
    - name: Récupération manifests
      copy:
        src: manifests
        dest: /
        owner: root
        group: root
        mode: "0644"

    - name: Ajout des manifests de base (authentification, ...)
      shell: kubectl apply -f /manifests

    # Cilium
    - name: Installation Cilium
      shell: helm install cilium cilium/cilium --namespace {{ cilium.namespace }} --set ipam.mode={{ cilium.ipam }} --set prometheus.enable={{ cilium.agentMetrics }} --set operator.prometheus.enable={{ cilium.operatorMetrics }}

    # OpenEBS
    # - name: Installation OpenEBS
    #   shell: helm install openebs openebs/openebs --namespace openebs --set ndm.filters.includePaths="/dev/sdc"

    - name: Installation OpenEBS
      shell: kubectl apply -f https://openebs.github.io/charts/cstor-operator.yaml

    - name: Vérification nodes
      shell: kubectl get nodes

    - name: Petite pause après pour la création des blockDevices...
      pause:
        seconds: "120"

    - name: Vérification OpenEBS
      shell: kubectl get pods -n openebs

    - name: Récupération des blockdevices disponibles
      block:
        - name: Récupération des blockdevices disponibles 1
          shell: kubectl get bd -n openebs --no-headers -o custom-columns=:metadata.name
          register: blockdevices
      rescue:
        - name: Récupération des blockdevices disponibles 2
          shell: kubectl get bd -n openebs --no-headers -o custom-columns=:metadata.name
          register: blockdevices

    - name: Création manifests OpenEBS
      template:
        src: "{{ item }}"
        dest: /manifests/
        group: root
        mode: "0644"
      with_fileglob:
        - "./templates/openebs*.yaml"

    - name: Création du pool cStor OpenEBS
      shell: kubectl apply -f /manifests/openebs-cstor.yaml

    - name: Petite pause pour la création de la cStor pool...
      pause:
        seconds: "40"

    - name: Création de la StorageClass OpenEBS
      shell: kubectl apply -f /manifests/openebs-storageclass.yaml

    # Monitoring (Prometheus / Grafana / Loki)
    - name: Création manifests Monitoring
      template:
        src: "{{ item }}"
        dest: /manifests/
        group: root
        mode: "0644"
      with_fileglob:
        - "../monitoring"

    - name: Retire les json des dashboard du dossier manifests
      shell: rm -R /manifests/monitoring/grafana/dashboard-json

    - name: Ajout des manifests Monitoring
      shell: kubectl apply -R -f /manifests/monitoring

    - name: Ajout de Loki
      shell: helm install loki loki/loki-stack -n monitoring

    # Monitoring Sécurité (Falco)
    - name: Ajout de la configuration Helm
      template:
        src: "{{ item }}"
        dest: /manifests/falco-values.yaml
        group: root
        mode: "0644"
      with_fileglob:
        - "../securite/Falco/values.yml"

    - name: Ajout de Falco
      shell: helm install falco falcosecurity/falco -n falco -f /manifests/falco-values.yaml
