apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
  - name: grafui
    nodePort: 30901
    protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort