apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secu-test
  name: namespace-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secu-test
  name: mamespace-create
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list","create"]

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secu-test
  name: namespace-admin-all
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]