apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    type: admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    type: admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: falco
  labels:
    type: admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: securite-des-echanges
  labels:
    promo: I3
    option: CSS
    type: TD
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure-vmware
  labels:
    promo: I3
    option: CSS
    type: TD
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructures-et-reseau
  labels:
    promo: I1
    type: TD
---
apiVersion: v1
kind: Namespace
metadata:
  name: somanager
  labels:
    promo: I3
    type: Projet
---
apiVersion: v1
kind: Namespace
metadata:
  name: capture-the-flag
  labels:
    promo: I3
    option: CSS
    type: Projet
