apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
        podSubnet: "{{ kubelet.network.podSubnet }}"
        serviceSubnet: "{{ kubelet.network.serviceSubnet }}"
controlPlaneEndpoint: "{{ kubelet.ha.haproxyIp }}:6443"
apiServer:
        extraArgs:
                oidc-client-id: "{{ kubelet.auth.oidc-client-id }}"
                oidc-issuer-url: "{{ kubelet.auth.oidc-issuer-url }}"
                oidc-username-claim: "{{ kubelet.auth.oidc-username-claim }}"
                oidc-username-prefix: "{{ kubelet.auth.oidc-username-prefix }}"
                oidc-groups-claim: "{{ kubelet.auth.oidc-groups-claim }}"
                oidc-groups-prefix: "{{ kubelet.auth.oidc-groups-prefix }}"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
