apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
        podSubnet: "{{ kubelet.network.podSubnet }}"
        serviceSubnet: "{{ kubelet.network.serviceSubnet }}"
controlPlaneEndpoint: "{{ kubelet.ha.haproxyIp }}:6443"
apiServer:
        extraArgs:
                oidc-client-id: "{{ kubelet.auth.oidcClientId }}"
                oidc-issuer-url: "{{ kubelet.auth.oidcIssuerURL }}"
                oidc-username-claim: "{{ kubelet.auth.oidcUsernameClaim }}"
                oidc-username-prefix: "{{ kubelet.auth.oidcUsernamePrefix }}"
                oidc-groups-claim: "{{ kubelet.auth.oidcGroupsClaim }}"
                oidc-groups-prefix: "{{ kubelet.auth.oidcGroupsPrefix }}"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
