---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool-global
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-disk-pool-global
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
    {% for bd in hostvars[groups['master'][0]].blockdevices %}
    - {{ bd }}
    {% endfor %}

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-global
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-disk-pool-global"
      - name: ReplicaCount
        value: "3"
provisioner: openebs.io/provisioner-iscsi