---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-global
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  cstorPoolCluster: cspc-stripe
  replicaCount: "3"
