---
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cspc-stripe
  namespace: openebs
spec:
  pools:
{% for bd in hostvars[groups['masters'][0]].blockdevices.stdout_lines %}
    - nodeSelector:
        kubernetes.io/hostname: {{ hostvars[groups['masters'][0]].blockdevices-nodes.stdout_lines[loop.index0] }}
      dataRaidGroups:
      - blockDevices:
          - blockDeviceName: {{ bd }}
      poolConfig:
        dataRaidGroupType: "stripe"
{% endfor %}
