# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Machine Routage
    config.vm.define "node4" do |machine|
        machine.vm.hostname = "node4"
        # Box de base (agent de supervision, tests, sécurité, ...)
        machine.vm.box = "ubuntu/focal64"
        # Désactive la synchronisation rsync
        machine.vm.synced_folder '.', '/vagrant', disabled: true
        machine.vm.network :public_network, bridge: "eno1", ip: "192.168.4.238", netmask: "255.255.255.0"
        machine.disksize.size = '50GB'
        machine.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--name", "node4"]
            v.customize ["modifyvm", :id, "--groups", "/pfe-kubernetes"]
            v.customize ["modifyvm", :id, "--cpus", "6"]
            v.customize ["modifyvm", :id, "--memory", 12288]
        end
        machine.vm.provision "shell", inline: <<-SHELL   
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            sleep 3
            service ssh restart
            useradd k8s --home /home/k8s/ --create-home --groups sudo --shell /bin/bash
            echo -e "network\nnetwork\n" | passwd k8s
            mkdir /etc/network/if-up.d
            echo -e "#!/bin/bash\nip route add 10.8.0.0/24 via 192.168.4.1 | true\nip route add 172.29.0.0/24 via 192.168.4.1 | true" >> /etc/network/if-up.d/vpn_routes
            echo -e "#!/bin/bash\nip route del 10.8.0.0/24 via 192.168.4.1 | true\nip route del 172.29.0.0/24 via 192.168.4.1 | true" >> /etc/network/if-down.d/vpn_routes
        SHELL
    end
    # Provisioning
 #   config.vm.provision :ansible do |ansible|
  #      ansible.playbook = "provisioning/playbook.yml"
   # end
end