apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ClusterReader
subjects: 
- kind: Group
  name: eseo:professeur
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: accessClusterReader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: accesssClusterAdmin
subjects:
- kind: User
  name: eseo:guillaume.cahagne@reseau.eseo.fr
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
