
## RoleBinding pour le cours d'infrastructures et reseau de I1, supervisé par monsieur chavin et administre par monsieur illias pillet
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-cours-infra-etu
  namespace: infrastructures-et-reseau
subjects:
- kind: Group
  name: eseo:I1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: access-cours-etudiant
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-cours-infra-prof
  namespace: infrastructures-et-reseau
subjects:
- kind: User
  name: eseo:jerome.chavin@eseo.fr
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: access-cours-prof
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-infra
  namespace: infrastructures-et-reseau
subjects:
- kind: User
  name: eseo:jonathan.illias@eseo.fr
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io
---

## RoleBinding pour le cours d'infrastructure VmWare de I3 donné par monsieur Jamet et administre par monsieur chavin et illias-pillet
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-cours-VmWare-etu
  namespace: infrastructure-VmWare
subjects:
- kind: Group
  name: eseo:CSS
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: access-cours-etudiant
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-cours-VmWare-prof
  namespace: infrastructure-VmWare
subjects:
- kind: User
  name: eseo:francois.jamet@eseo.fr
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: access-cours-prof
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-VmWare
  namespace: infrastructure-VmWare
subjects:
- kind: User
  name: eseo:jonathan.illias@eseo.fr
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: eseo:jerome.chavin@eseo.fr  
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io