## Role pour les namespaces pour les edutiants, professeur qui font le cours, et administrateur du cours

## Cours d'infrastructure et reseau de I1
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: infrastructures-et-reseau
  name: access-cours-etudiant
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: infrastructures-et-reseau 
  name: access-cours-prof
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: infrastructures-et-reseau
  name: namespace-admin
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---  
## Cours dinfrastructure VmWare de I3
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: infrastructure-VmWare
  name: access-cours-etudiant
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: infrastructure-VmWare 
  name: access-cours-prof
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: infrastructure-VmWare
  name: namespace-admin
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---  
## Cours de securite des echanges de I3
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: securite-des-echanges
  name: access-cours-etudiant
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: securite-des-echanges 
  name: access-cours-prof
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: securite-des-echanges
  name: namespace-admin
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---  
## Projet de SoManager de I2
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: SoManager
  name: access-etudiant
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: SoManager 
  name: access-prof
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: SoManager
  name: namespace-admin
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---  
## Projet capture the flag de I3
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: capture-the-flag
  name: access-etudiant
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: capture-the-flag 
  name: access-prof
rules:
- apiGroups: [""]
  resources: ["deployments","pods","configmaps","services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: capture-the-flag
  name: namespace-admin
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---  