## Network Policy 

## Les exporter ne peuvent communiquer qu'avec prometheus  
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-exporter-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: exporter
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: prometheus

---
## Le trafic au sein du namespace "projet" est limité à ce namespace et à l'accès au DNS et à l'accès de prometheus
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-within-namespace"
specs:
  - endpointSelector:
      matchLabels: {} 
    egress:
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": projet
    ingress:
    - fromEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": projet
  - endpointSelector:
      matchLabels: {} 
    egress:
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
  - endpointSelector:
      matchLabels: {} 
    ingress:
    - fromEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": monitoring
          app: prometheus
      toPorts:
      - ports:
        - port: "8080"
          protocol: "TCP"
        rules:
          http:
          - method: "GET"
            path: "/metrics"

