{
 "title": "Kubernetes network",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Forwarded bytes by direction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_bytes_total{direction=\"EGRESS\"}[$__rate_interval]))",
     "legendFormat": "Egress"
    },
    {
     "expr": "sum(rate(cilium_forward_bytes_total{direction=\"INGRESS\"}[$__rate_interval]))",
     "legendFormat": "Ingress"
    }
   ]
  },
  {
   "title": "IPv4 Addresses in use",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "IPs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cilium_ip_addresses{family=\"ipv4\"})"
    }
   ]
  },
  {
   "title": "List of nodes and network reachability",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "cilium_unreachable_nodes" }
   ]
  },
  {
   "title": "Bytes dropped by reason",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"INGRESS\"}[$__rate_interval])) by (reason)",
     "legendFormat": "ingress ({{reason}})"
    },
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"EGRESS\"}[$__rate_interval])) by (reason)",
     "legendFormat": "egress ({{reason}})"
    }
   ]
  },
  {
   "title": "Number of dropped packets",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total[$__rate_interval])) by (reason)",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum(rate(cilium_drop_count_total[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}