{
 "title": "Falco",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rule",
    "query": "label_values(falco_events, rule)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate of events for rule: $rule",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "repeat": "rule",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(falco_events{rule=\"$rule\"}[$__rate_interval])",
     "legendFormat": "[{{k8s_ns_name}}] {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Rate of events for rule: $rule",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(falco_events{rule=\"$rule\"}[$__rate_interval])",
     "legendFormat": "[{{k8s_ns_name}}] {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(falco_events) by (rule)", "legendFormat": "{{rule}}" }
   ]
  },
  {
   "title": "Events rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(falco_events[5m])) by (rule)",
     "legendFormat": "{{rule}} (node=\"{{kubernetes_node}}\",ns=\"{{k8s_ns_name}}\",pod=\"{{k8s_pod_name}}\")"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "falco_events" }
   ]
  }
 ]
}