{
 "title": "OpenEBS Dashboard",
 "description": "This dashboard gives overview of OpenEBS installation in cluster.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "label_values(up,cluster)" },
   {
    "name": "duration",
    "query": "10m,1h,3h,12h,1d,3d,5d,7d,10d,14d,21d,30d"
   },
   {
    "name": "namespace",
    "query": "openebs, monitoring, wordpress, default, secu-test"
   }
  ]
 },
 "panels": [
  {
   "title": "OpenEBS version",
   "type": "singlestat",
   "description": "This panel shows the version of OpenEBS running on $cluster cluster.  OpenEBS provides storage for stateful workloads in $cluster cluster.",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "abs(openebs_maya_exporter_version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "OpenEBS data plane availability over [$duration]",
   "type": "singlestat",
   "description": "OpenEBS SLO is based on no. of running data plane OpenEBS pods over a period of time. Below pods have been taken into consideration which impacts data availability hosted on OpenEBS:\n\n1. cstor pods\n2. jiva ctrl and replica pods\n3. nfs provisioner\n",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "displayType": "Regular",
     "expr": "avg(avg_over_time((sum without ()(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"openebs\",pod=~\"pvc.*.ctrl.*|pvc.*.rep.*|pvc.*.target.*\"}) / count without ()(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"openebs\",pod=~\"pvc.*.ctrl.*|pvc.*.rep.*|pvc.*.target.*\"}))[$duration:5m]))",
     "valueHandler": "Number Threshold"
    },
    {}
   ]
  },
  {
   "title": "Ready pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOMKilled pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{cluster=\"$cluster\",reason=\"OOMKilled\",namespace=\"$namespace\"} != 0 ) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{cluster=\"$cluster\",namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Readonly PVC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly{cluster=\"$cluster\",namespace=\"$namespace\"} != 0) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Besteffort  pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",id=~\"/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "burstable  pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",id=~\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory details in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " (sum(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\", namespace=\"$namespace\"}))",
     "legendFormat": "Memory used"
    },
    {
     "expr": " (sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}))",
     "legendFormat": "Memory requests"
    },
    {
     "expr": " (sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}))",
     "legendFormat": "Memory limits"
    }
   ]
  },
  {
   "title": "CPU  details in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",pod!=\"\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "CPU used"
    }
   ]
  },
  {
   "title": "PVCs available capacity in namespace $namespace",
   "type": "bargauge",
   "description": "\n",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"$namespace\"}\n  / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": " kube_pod_container_status_ready{namespace=\"$namespace\"} == 1"
    },
    {
     "expr": "sum\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",namespace=\"$namespace\"})"
    },
    {
     "expr": "kube_pod_info{namespace=\"$namespace\"}"
    },
    {
     "expr": "time() - kube_pod_start_time{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory usage by Pods in OpenEBS  in $cluster cluster",
   "type": "graph",
   "description": "This panel shows mem usage of  pods across $namespace in $cluster cluster.\n\nMemory utilization is easily tracked with container_memory_usage_bytes, however, this metric also includes cached (think filesystem cache) items that can be evicted under memory pressure. That's why we are using a  better metric: container_memory_working_set_bytes as this is what the OOM killer is watching for.\n",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": " (sum(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod_name))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU usage by Pods in OpenEBS  in $cluster cluster",
   "type": "graph",
   "description": "This panel shows mem usage of  pods across $namespace in $cluster cluster.\n\nMemory utilization is easily tracked with container_memory_usage_bytes, however, this metric also includes cached (think filesystem cache) items that can be evicted under memory pressure. That's why we are using a  better metric: container_memory_working_set_bytes as this is what the OOM killer is watching for.\n",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",pod!=\"\",namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "pod count by nodes of $namespace in $cluster cluster",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (node)(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "pod container restarts in OpenEBS in $duration",
   "type": "graph",
   "description": "This panel shows container restarts in $cluster cluster per namespace during $duration.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=\"$namespace\"}[2m]) ",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Waiting/Terminated pods in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(pod,reason) (kube_pod_container_status_terminated_reason{cluster=\"$cluster\",namespace=\"$namespace\",reason!=\"Completed\"} !=0 )",
     "legendFormat": "TERMINATED::{{reason}}::{{pod}}"
    },
    {
     "expr": "count by(pod,reason) (kube_pod_container_status_waiting_reason{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 )",
     "legendFormat": "WAITING::{{reason}}::{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "persistentvolumeclaim in namespace $namespace",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\"}",
     "legendFormat": "{{persistentvolumeclaim}}:{{phase}}"
    }
   ]
  },
  {
   "title": "$cluster OpenEBS replicas",
   "type": "stat",
   "description": "This panel shows if there is any unhealthy OpenEBS  replicas on $cluster cluster.\n\n",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(openebs_total_replica_count{cluster=\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}