---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4-overrides:
        use-dns: false
        use-routes: false
    enp0s8:
      dhcp4: false
      nameservers:
        addresses:
        - 192.168.4.2
      routes:
      - to: 172.29.0.0/24
        via: 192.168.4.1
      - to: 0.0.0.0/0
        via: 192.168.4.1
